version: 2

build:
  os: 'ubuntu-22.04'
  tools:
    python: '3.12'

sphinx:
  configuration: 'doc/source/conf.py'
  fail_on_warning: true

python:
  install:
    - requirements: 'doc/requirements.txt'
